[package]
name = "rustnes"
version = "0.1.0"
edition = "2021"

[dependencies]
bitflags = "2.9.0"
lazy_static = "1.5.0"
rand = "0.9.1"
sdl2 = "0.37.0"

[[bin]]
name = "main"
path = "src/main.rs"

[[bin]]
name = "tile"
path = "src/test_tile.rs"
